const foods = [
  {
    id: 12,
    name: 'Meat Pizza',
    ingredients: 'Mixed Pizza',
    price: '20.000d',
    image: require('../assets/meatPizza.png'),
  },
  {
    id: 11,
    name: 'Cheese Pizza',
    ingredients: 'Cheese Pizza',
    price: '22.000d',
    image: require('../assets/cheesePizza.png'),
  },
  {
    id: 3,
    name: 'Chicken Burger',
    ingredients: 'Fried Chicken',
    price: '23.000d',
    image: require('../assets/chickenBurger.png'),
  },
  {
    id: 4,
    name: 'Sushi Makizushi',
    ingredients: 'Salmon Meat',
    price: '100.000d',
    image: require('../assets/sushiMakizushi.png'),
  },
  {
    id: 5,
    name: 'Meat Pizza',
    ingredients: 'Mixed Pizza',
    price: '20.000d',
    image: require('../assets/meatPizza.png'),
  },
  {
    id: 6,
    name: 'Cheese Pizza',
    ingredients: 'Cheese Pizza',
    price: '22.000d',
    image: require('../assets/cheesePizza.png'),
  },
  {
    id: 7,
    name: 'Chicken Burger',
    ingredients: 'Fried Chicken',
    price: '23.000d',
    image: require('../assets/chickenBurger.png'),
  },
  {
    id: 8,
    name: 'Sushi Makizushi',
    ingredients: 'Salmon Meat',
    price: '100.000d',
    image: require('../assets/sushiMakizushi.png'),
  },
  {
    id: 9,
    name: 'Meat Pizza',
    ingredients: 'Mixed Pizza',
    price: '20.000d',
    image: require('../assets/meatPizza.png'),
  },
  {
    id: 10,
    name: 'Cheese Pizza',
    ingredients: 'Cheese Pizza',
    price: '22.000d',
    image: require('../assets/cheesePizza.png'),
  },
  {
    id: 1,
    name: 'Chicken Burger',
    ingredients: 'Fried Chicken',
    price: '23.000d',
    image: require('../assets/chickenBurger.png'),
  },
  {
    id: 2,
    name: 'Sushi Makizushi',
    ingredients: 'Salmon Meat',
    price: '100.000d',
    image: require('../assets/sushiMakizushi.png'),
  },
];

export default foods;
